namespace Day_3_Tests;

public static class EngineSchematicTestData
{
    public static IEnumerable<int> TestPartNumbers = new List<int> { 467, 35, 633, 617, 592, 755, 664, 598 };
    
    public static EngineSchematicCell[][] TestMatrix = [
                [
                    new EngineSchematicCell { RowIndex = 0, Digit = "4", ColumnIndex = 0, IsStartDigit = true },
                    new EngineSchematicCell { RowIndex = 0, Digit = "6", ColumnIndex = 1 },
                    new EngineSchematicCell { RowIndex = 0, Digit = "7", ColumnIndex = 2, IsAdjacentToSymbol = true },
                    new EngineSchematicCell { RowIndex = 0, ColumnIndex = 3 },
                    new EngineSchematicCell { RowIndex = 0, ColumnIndex = 4 },
                    new EngineSchematicCell { RowIndex = 0, Digit = "1", ColumnIndex = 5, IsStartDigit = true },
                    new EngineSchematicCell { RowIndex = 0, Digit = "1", ColumnIndex = 6 },
                    new EngineSchematicCell { RowIndex = 0, Digit = "4", ColumnIndex = 7 },
                    new EngineSchematicCell { RowIndex = 0, ColumnIndex = 8 },
                    new EngineSchematicCell { RowIndex = 0, ColumnIndex = 9 },
                ],
                [
                    new EngineSchematicCell { RowIndex = 1, ColumnIndex = 0 },
                    new EngineSchematicCell { RowIndex = 1, ColumnIndex = 1 },
                    new EngineSchematicCell { RowIndex = 1, ColumnIndex = 2 },
                    new EngineSchematicCell { RowIndex = 1, ColumnIndex = 3, IsSymbol = true },
                    new EngineSchematicCell { RowIndex = 1, ColumnIndex = 4 },
                    new EngineSchematicCell { RowIndex = 1, ColumnIndex = 5 },
                    new EngineSchematicCell { RowIndex = 1, ColumnIndex = 6 },
                    new EngineSchematicCell { RowIndex = 1, ColumnIndex = 7 },
                    new EngineSchematicCell { RowIndex = 1, ColumnIndex = 8 },
                    new EngineSchematicCell { RowIndex = 1, ColumnIndex = 9 },
                ],
                [
                    new EngineSchematicCell { RowIndex = 2, ColumnIndex = 0 },
                    new EngineSchematicCell { RowIndex = 2, ColumnIndex = 1 },
                    new EngineSchematicCell { RowIndex = 2, Digit = "3", ColumnIndex = 2, IsStartDigit = true, IsAdjacentToSymbol = true },
                    new EngineSchematicCell { RowIndex = 2, Digit = "5", ColumnIndex = 3, IsAdjacentToSymbol = true },
                    new EngineSchematicCell { RowIndex = 2, ColumnIndex = 4 },
                    new EngineSchematicCell { RowIndex = 2, ColumnIndex = 5 },
                    new EngineSchematicCell { RowIndex = 2, Digit = "6", ColumnIndex = 6, IsStartDigit = true, IsAdjacentToSymbol = true },
                    new EngineSchematicCell { RowIndex = 2, Digit = "3", ColumnIndex = 7, IsAdjacentToSymbol = true },
                    new EngineSchematicCell { RowIndex = 2, Digit = "3", ColumnIndex = 8 },
                    new EngineSchematicCell { RowIndex = 2, ColumnIndex = 9 },
                ],
                [
                    new EngineSchematicCell { RowIndex = 3, ColumnIndex = 0},
                    new EngineSchematicCell { RowIndex = 3, ColumnIndex = 1 },
                    new EngineSchematicCell { RowIndex = 3, ColumnIndex = 2 },
                    new EngineSchematicCell { RowIndex = 3, ColumnIndex = 3 },
                    new EngineSchematicCell { RowIndex = 3, ColumnIndex = 4 },
                    new EngineSchematicCell { RowIndex = 3, ColumnIndex = 5 },
                    new EngineSchematicCell { RowIndex = 3, ColumnIndex = 6, IsSymbol = true },
                    new EngineSchematicCell { RowIndex = 3, ColumnIndex = 7 },
                    new EngineSchematicCell { RowIndex = 3, ColumnIndex = 8 },
                    new EngineSchematicCell { RowIndex = 3, ColumnIndex = 9 },
                ],
                [
                    new EngineSchematicCell { RowIndex = 4, Digit = "6", ColumnIndex = 0, IsStartDigit = true },
                    new EngineSchematicCell { RowIndex = 4, Digit = "1", ColumnIndex = 1 },
                    new EngineSchematicCell { RowIndex = 4, Digit = "7", ColumnIndex = 2, IsAdjacentToSymbol = true },
                    new EngineSchematicCell { RowIndex = 4, ColumnIndex = 3, IsSymbol = true },
                    new EngineSchematicCell { RowIndex = 4, ColumnIndex = 4 },
                    new EngineSchematicCell { RowIndex = 4, ColumnIndex = 5 },
                    new EngineSchematicCell { RowIndex = 4, ColumnIndex = 6 },
                    new EngineSchematicCell { RowIndex = 4, ColumnIndex = 7 },
                    new EngineSchematicCell { RowIndex = 4, ColumnIndex = 8 },
                    new EngineSchematicCell { RowIndex = 4, ColumnIndex = 9 },
                ],
                [
                    new EngineSchematicCell { RowIndex = 5, ColumnIndex = 0 },
                    new EngineSchematicCell { RowIndex = 5, ColumnIndex = 1 },
                    new EngineSchematicCell { RowIndex = 5, ColumnIndex = 2 },
                    new EngineSchematicCell { RowIndex = 5, ColumnIndex = 3 },
                    new EngineSchematicCell { RowIndex = 5, ColumnIndex = 4, },
                    new EngineSchematicCell { RowIndex = 5, ColumnIndex = 5, IsSymbol = true },
                    new EngineSchematicCell { RowIndex = 5, ColumnIndex = 6 },
                    new EngineSchematicCell { RowIndex = 5, Digit = "5", ColumnIndex = 7, IsStartDigit  = true },
                    new EngineSchematicCell { RowIndex = 5, Digit = "8", ColumnIndex = 8 },
                    new EngineSchematicCell { RowIndex = 5, ColumnIndex = 9 },
                ],
                [
                    new EngineSchematicCell { RowIndex = 6, ColumnIndex = 0 },
                    new EngineSchematicCell { RowIndex = 6, ColumnIndex = 1 },
                    new EngineSchematicCell { RowIndex = 6, Digit = "5", ColumnIndex = 2, IsStartDigit = true },
                    new EngineSchematicCell { RowIndex = 6, Digit = "9", ColumnIndex = 3 },
                    new EngineSchematicCell { RowIndex = 6, Digit = "2", ColumnIndex = 4, IsAdjacentToSymbol = true },
                    new EngineSchematicCell { RowIndex = 6, ColumnIndex = 5 },
                    new EngineSchematicCell { RowIndex = 6, ColumnIndex = 6 },
                    new EngineSchematicCell { RowIndex = 6, ColumnIndex = 7 },
                    new EngineSchematicCell { RowIndex = 6, ColumnIndex = 8 },
                    new EngineSchematicCell { RowIndex = 6, ColumnIndex = 9 },
                ],
                [
                    new EngineSchematicCell { RowIndex = 7, ColumnIndex = 0 },
                    new EngineSchematicCell { RowIndex = 7, ColumnIndex = 1 },
                    new EngineSchematicCell { RowIndex = 7, ColumnIndex = 2 },
                    new EngineSchematicCell { RowIndex = 7, ColumnIndex = 3 },
                    new EngineSchematicCell { RowIndex = 7, ColumnIndex = 4 },
                    new EngineSchematicCell { RowIndex = 7, ColumnIndex = 5 },
                    new EngineSchematicCell { RowIndex = 7, Digit = "7", ColumnIndex = 6, IsStartDigit = true, IsAdjacentToSymbol = true },
                    new EngineSchematicCell { RowIndex = 7, Digit = "5", ColumnIndex = 7 },
                    new EngineSchematicCell { RowIndex = 7, Digit = "5", ColumnIndex = 8 },
                    new EngineSchematicCell { RowIndex = 7, ColumnIndex = 9 },
                ],
                [
                    new EngineSchematicCell { RowIndex = 8, ColumnIndex = 0 },
                    new EngineSchematicCell { RowIndex = 8, ColumnIndex = 1 },
                    new EngineSchematicCell { RowIndex = 8, ColumnIndex = 2 },
                    new EngineSchematicCell { RowIndex = 8, ColumnIndex = 3, IsSymbol = true },
                    new EngineSchematicCell { RowIndex = 8, ColumnIndex = 4 },
                    new EngineSchematicCell { RowIndex = 8, ColumnIndex = 5, IsSymbol = true },
                    new EngineSchematicCell { RowIndex = 8, ColumnIndex = 6 },
                    new EngineSchematicCell { RowIndex = 8, ColumnIndex = 7 },
                    new EngineSchematicCell { RowIndex = 8, ColumnIndex = 8 },
                    new EngineSchematicCell { RowIndex = 8, ColumnIndex = 9 },
                ],
                [
                    new EngineSchematicCell { RowIndex = 9, ColumnIndex = 0 },
                    new EngineSchematicCell { RowIndex = 9, Digit = "6", ColumnIndex = 1,  IsStartDigit = true },
                    new EngineSchematicCell { RowIndex = 9, Digit = "6", ColumnIndex = 2, IsAdjacentToSymbol = true },
                    new EngineSchematicCell { RowIndex = 9, Digit = "4", ColumnIndex = 3, IsAdjacentToSymbol = true },
                    new EngineSchematicCell { RowIndex = 9, ColumnIndex = 4, },
                    new EngineSchematicCell { RowIndex = 9, Digit = "5", ColumnIndex = 5,  IsStartDigit = true, IsAdjacentToSymbol = true },
                    new EngineSchematicCell { RowIndex = 9, Digit = "9", ColumnIndex = 6, IsAdjacentToSymbol = true },
                    new EngineSchematicCell { RowIndex = 9, Digit = "8", ColumnIndex = 7 },
                    new EngineSchematicCell { RowIndex = 9, ColumnIndex = 8 },
                    new EngineSchematicCell { RowIndex = 9, ColumnIndex = 9 },
                ],
            ];
}
